export const MockData = [
  {
    orderNumber: "ORD001",
    shipmentNumber: "SHIP001",
    platform: "Amazon",
    shipmentStatus: "Delivered",
    client: "John Doe",
    trackingNumber: "TRK001",
    trackingUrl: "https://trackingurl.com/TRK001",
    downloaded: false,
  },
  {
    orderNumber: "ORD002",
    shipmentNumber: "SHIP002",
    platform: "eBay",
    shipmentStatus: "In Transit",
    client: "Jane Smith",
    trackingNumber: "TRK002",
    trackingUrl: "https://trackingurl.com/TRK002",
    downloaded: true,
  },
  {
    orderNumber: "ORD003",
    shipmentNumber: "SHIP003",
    platform: "Shopify",
    shipmentStatus: "Pending",
    client: "Alice Johnson",
    trackingNumber: "TRK003",
    trackingUrl: "https://trackingurl.com/TRK003",
    downloaded: false,
  },
  {
    orderNumber: "ORD004",
    shipmentNumber: "SHIP004",
    platform: "Walmart",
    shipmentStatus: "Delivered",
    client: "Bob Lee",
    trackingNumber: "TRK004",
    trackingUrl: "https://trackingurl.com/TRK004",
    downloaded: true,
  },
  {
    orderNumber: "ORD005",
    shipmentNumber: "SHIP005",
    platform: "Etsy",
    shipmentStatus: "Cancelled",
    client: "Charlie Brown",
    trackingNumber: "TRK005",
    trackingUrl: "https://trackingurl.com/TRK005",
    downloaded: false,
  },
];
